LOG_LEVEL: DEBUG

ITERATIONS: 2000
SEED: 5243987

ORDER_ID:
  first_entry: 254781069873
  step: 1354
  multiplier: 1
  # 549755813887 decimal = 7FFFFFFFFF hex
  max_entry: 549755813887

PROVIDER_ID:
  first_entry: 0
  step: 0.33
  multiplier: 1.333
  values:
    - SQM
    - FXCM

DIRECTION:
  first_entry: 0
  step: 0.77
  multiplier: 1.333
  values:
    - Buy
    - Sell

CURRENCY_PAIR:
  first_entry: 0
  step: 0.77
  multiplier: 1.333
  values:
    - "EUR/USD": 1.120199
    - "GBP/USD": 1.304649
    - "USD/CHF": 0.984286
    - "USD/JPY": 112.175823
    - "AUD/USD": 0.677025
    - "NZD/USD": 0.648999
    - "CAD/CHF": 0.744244
    - "CAD/JPY": 84.706831
    - "CHF/JPY": 114.252908
    - "EUR/AUD": 1.712235
    - "EUR/CAD": 1.502292
    - "EUR/CHF": 1.072143
    - "EUR/GBP": 0.874086
    - "EUR/JPY": 121.346875
    - "EUR/NZD": 1.787336
    - "GBP/AUD": 1.981400
    - "GBP/CAD": 1.732194
    - "NZD/CAD": 0.861681
    - "NZD/CHF": 0.631029
    - "NZD/JPY": 71.310905
  delta:
    first_entry: 0
    step: 0.000023
    multiplier: 1.000033
    max_entry: 0.000999
  delta_partially_filled:
    first_entry: 0
    step: 0.000076
    multiplier: 1.000077
    max_entry: 0.000999
  px_vol:
    first_entry: 456.32
    step: 23
    multiplier: 1.03
    max_entry: 9999.99

ZONES:
  RED:
    statuses:
      - - To Provider
        - Rejected
      - - To Provider
        - Filled
      - - Rejected
      - - Partially Filled
      - - Filled
      - - Partially Filled
        - Filled
      - - To Provider
        - Partially Filled
  GREEN:
    statuses:
      - - New
        - To Provider
        - Partially Filled
        - Filled
      - - New
        - To Provider
        - Filled
      - - New
        - To Provider
        - Partially filled
      - - New
        - To Provider
        - Rejected
  BLUE:
    statuses:
      - - New
      - - New
        - To Provider
      - - New
        - To Provider
        - Partially Filled

DATE:
  first_entry: