DEFAULT_DATE_FORMAT = '%Y-%m-%d %H:%M:%S.%f'
HEX_BASE = 16
DEFAULT_ORDER_ID_HEX_STRING = 'deadbeef01'
DEFAULT_ORDER_ID_INCREMENT_RAND_RANGE = 10, 20
DEFAULT_CURRENCY_RANDOM_RANGE_DELTA = 0.000001, 0.00001
DEFAULT_TIME_DELTA = 1, 3
DEFAULT_ROUND = 6
GENERATOR_CONFIG_VALID_TYPES = {
    'TOTAL_ORDER': int,
    'INITIAL_ORDER_ID': type(str),
    'PROVIDER_ID': type(list),
    'DIRECTION': type(list),
    'CURRENCY_PAIR': type(dict),
    'ZONES': type(dict)
}
DEFAULT_VOL_RANGE = 100, 9999
DEFAULT_VOL_ROUND = 2
