ITERATIONS = 'ITERATIONS'

# DICT KEYS
FIRST_ENTRY = 'first_entry'
STEP = 'step'
MULTIPLIER = 'multiplier'
MAX_ENTRY = 'max_entry'
VALUES = 'values'

# CONFIG
ORDER_ID = 'ORDER_ID'
PROVIDER_ID = 'PROVIDER_ID'
DIRECTION = 'DIRECTION'
CURRENCY_PAIR = 'CURRENCY_PAIR'
STATUS = 'STATUS'
RED = 'RED'
GREEN = 'GREEN'
BLUE = 'BLUE'
